#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TimeTracker.Resource", IsApplication=true)]

namespace TimeTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_refresh = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int LinearLayout01 = 2131099662;
			
			// aapt resource value: 0x7f06001f
			public const int action_LogOut = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int action_profile = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int action_settings = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int action_wifi = 2131099678;
			
			// aapt resource value: 0x7f060005
			public const int btnKycu = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int btnRegjistrohu = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int btnRuaj = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int btnShtoKompani = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int check = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int imgRefreshData = 2131099659;
			
			// aapt resource value: 0x7f060019
			public const int label = 2131099673;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout2 = 2131099660;
			
			// aapt resource value: 0x7f06001b
			public const int listBeforeToday = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int listToday = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int listView = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int listViewWifi = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int refreshNetwork = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int spCompanySettings = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int spCompanywifi = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int spKompania = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int tabhost = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int textView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int textView3 = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int txtEmri = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int txtEmriMain = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int txtMbiemri = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int txtMbiemriMain = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int txtPassword = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int txtUsername = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_android_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_logIn = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_main2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_personal_data = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_settings = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_wi_fi_test = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int rowbuttonlayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int tab_activity1 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int tab_activity2 = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int settings = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
